import { NextApiRequest, NextApiResponse } from 'next';
import { OpenAI } from 'openai';

console.log('🔐 Loaded OPENAI_API_KEY:', process.env.OPENAI_API_KEY ? '✅ Loaded' : '❌ Missing');

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const { niche, platform, audience, tone, goal, product, pain, format } = req.body || {};

  if (!niche || !platform || !audience || !tone || !goal || !format) {
    return res.status(400).json({ error: 'Missing required fields in request body.' });
  }

  try {
    const sanitizedFormat = typeof format === 'string' ? format.toLowerCase() : 'content';

    const prompt = `
You're a world-class brand strategist and content marketing expert.

Your task is to create marketing content that:
- Feels professionally written and emotionally compelling
- Is tailored to the user's niche, audience, and product
- Explains the strategic reasoning behind each section

FORMAT: ${format}

USER INPUT:
Niche: ${niche}
Platform: ${platform}
Audience: ${audience}
Tone: ${tone}
Goal: ${goal}
Product: ${product || 'Not specified'}
Customer Pain Point: ${pain || 'Not specified'}

DELIVER THE FOLLOWING SECTIONS:

1. **Captions**
Generate 3 unique, scroll-stopping ${sanitizedFormat}s optimized for ${platform}. Match the tone "${tone}" and include relevant hashtags if appropriate.

2. **Hook Ideas**
Write 3 attention-grabbing hooks to use as opening lines or intro text. Use curiosity or emotional triggers.

3. **Content Strategy Tip**
Give one tactical tip to improve performance for this format. Focus on trends, timing, formats, or creative approach.

4. **Why This Works**
Explain why these examples work — reference psychology, copywriting principles, audience targeting, or structure. Speak like a strategist, not an AI.

Make the content feel premium, insightful, and useful to a content creator or brand builder.
    `;

    const response = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
    });

    const output = response.choices?.[0]?.message?.content;
    console.log('🔵 OpenAI raw output:', output);

    if (!output || output.trim() === '') {
      return res.status(500).json({ error: 'No content generated by OpenAI.' });
    }

    return res.status(200).json({ result: output });
  } catch (error: any) {
    console.error('❌ OpenAI API Error:', error?.message || error);
    return res.status(500).json({ error: 'Failed to connect to OpenAI. Check API key and request payload.' });
  }
}
